version: "3.1"

services:
    
    webserver:
        image: nginx:alpine
        container_name: brew-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - "8001:80"
        depends_on: 
            - php-fpm
        networks: 
            - backend
            - frontend
    
    # @todo Add specific development reqs xdebug etc
    php-fpm:
        build:
            context: ./docker
            dockerfile: DockerFile-php-fpm
        container_name: brew-php-fpm
        volumes: 
            - .:/application

        depends_on: 
            - mariadb
            - redis
        networks: 
            - backend
    
    redis:
        image: redis:3.2-alpine
        container_name: brew-redis
        networks: 
            - backend
    
    mariadb:
        image: mariadb:10.3
        container_name: brew-mariadb
        volumes: 
            - brew-mariadb:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: password123
            MYSQL_USER: brew-dbuser
            MYSQL_PASSWORD: brew-dbpassword
            MYSQL_DATABASE: brew
        ports:
            - "3308:3306"
        networks: 
            - backend

volumes: 
    brew-mariadb:

networks: 
    frontend:
    backend:        